# 张量 (Tensor)
数学中指的是多维数组；

# torch.Tensor 
data: 被封装的 Tensor
dtype: 张量的数据类型
shape: 张量的形状
device: 张量所在的设备，GPU/CPU
requires_grad: 指示是否需要计算梯度
grad: data 的梯度
grad_fn: 创建 Tensor 的 Function，是自动求导的关键
is_leaf: 指示是否是叶子结点

# 创建张量
## 直接创建
### 1. 从 data 创建 tensor

data: 可以是 list, numpy
dtype: 数据类型，默认与data一致
device: 所在设备
requires_grad: 是否需要梯度
pin_memory: 是否存于锁页内存

```python
torch.tensor(
    data,
    dtype=None,
    device=None,
    requires_grad=False,
    pin_memory=False
)
```

### 2. 从 numpy 创建 tensor
用 torch.from_numpy()创建的tensor与原始的ndarray共享内存，修改其中一个，另一个也会变。

```python
torch.from_numpy(ndarray)
```

In [5]:
import torch
import numpy as np

# 直接创建
## torch.tensor()
arr = np.ones((3,3))
t = torch.tensor(arr, 
                 dtype=torch.float32, 
                 device="mps") # 把张量放到 GPU 上 (mac M1)

print(t.dtype)
print(t)


## torch.from_numpy()
arr = np.array([[1,2,3],[4,5,6]])
t = torch.from_numpy(arr)
print(t.dtype)
print(t)

torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='mps:0')
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


## 根据数值进行创建

torch.zeros()
创建全0张量

size: 张量的形状。
out: 输出的张量 (暂时可以不考虑)。
layout:内存中布局形式，有 strided (通常情况下使用), sparse_coo (读取稀疏矩阵会用到)。
device: 所在设备。
requires_grad: 是否需要梯度。

```python
torch.zeros(
    *size,
    out=None,
    dtype=None,
    layout=torch.strided,
    device=False,
    requires_grad=False
)
```

torch.zeros_lisk()
根据 input 形状创建全0张量
input: 创建与 input 同形状的张量；
dtype: 数据类型；
layout: 内存中的布局形式；

```python
torch.zeros_like(
    input,
    dtype=None,
    layout=None,
    device=None,
    requires_grad=False
)
```

`torch.ones()` 和 `torch.ones_like()`
 创建全1张量


`torch.full()`和`torch.full_like()`
创建自定义数值的张量
size: 张量形状
fill_value: 张量的值


`torch.arange()`
根据数列创建等差1维张量，[start, end)
start: 起始值
end: 结束值
step: 数列公差，默认为1

`torch.linspace()`
创建均分的1维张量，[start, end]
start: 起始值
end: 结束值
step: 数列长度

In [8]:
t = torch.zeros((3,3))
print(t.dtype)
print(t)

t = torch.full((3,3),2) # 创建3x3的全2张量
print(t)

t = torch.arange(2, 8, 2)
print(t)

t = torch.linspace(2, 10, 5)
print(t)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
tensor([2, 4, 6])
tensor([ 2.,  4.,  6.,  8., 10.])
